name: deploy-model-training-pipeline

on:
  workflow_dispatch:

jobs:
  get-config:
    uses: Azure/mlops-templates/.github/workflows/read-yaml.yml@main
    with:
      file_name: config-infra-prod.yml
  create-compute-standard:
    needs: get-config
    uses: ./.github/workflows/create-compute.yml
    with:
      cluster_name: cpu-cluster
      size: STANDARD_DS3_V2
      min_instances: 0
      max_instances: 1
      resource_group: ${{ needs.get-config.outputs.resource_group }}
      workspace_name: ${{ needs.get-config.outputs.aml_workspace }}
    secrets:
      client-id: ${{ secrets.AZURE_CLIENT_ID }}
      tenant-id: ${{ secrets.AZURE_TENANT_ID }}
      subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
  register-environment:
    needs:
      [
        get-config,
        create-compute-standard
      ]
    uses: ./.github/workflows/register-environment.yml
    with:
      resource_group: ${{ needs.get-config.outputs.resource_group }}
      workspace_name: ${{ needs.get-config.outputs.aml_workspace }}
      environment_file: mlops/azureml/train/train-env.yaml
    secrets:
      client-id: ${{ secrets.AZURE_CLIENT_ID }}
      tenant-id: ${{ secrets.AZURE_TENANT_ID }}
      subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
  run-pipeline:
    needs:
      [
        get-config,
        create-compute-standard
        register-environment,
      ]
    uses: ./.github/workflows/run-pipeline.yml
    with:
      resource_group: ${{ needs.get-config.outputs.resource_group }}
      workspace_name: ${{ needs.get-config.outputs.aml_workspace }}
      parameters-file: mlops/azureml/train/pipeline.yml
      job-name: nlp_summerization
    secrets:
      client-id: ${{ secrets.AZURE_CLIENT_ID }}
      tenant-id: ${{ secrets.AZURE_TENANT_ID }}
      subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
