name: deploy-online-endpoint-pipeline

on: 
  workflow_dispatch:

jobs:
  get-config:
      uses: Azure/mlops-templates/.github/workflows/read-yaml.yml@main
      with:
        file_name: config-infra-prod.yml
  create-endpoint:
      needs: get-config
      uses: ./.github/workflows/create-endpoint.yml
      with:
        resource_group: ${{ needs.get-config.outputs.resource_group }}
        workspace_name: ${{ needs.get-config.outputs.aml_workspace }} 
        endpoint_file: mlops/azureml/deploy/online/online-endpoint.yml
        endpoint_name: nlp-summarization-online-dp
        endpoint_type: online
      secrets:
            client-id: ${{ secrets.AZURE_CLIENT_ID }}
            tenant-id: ${{ secrets.AZURE_TENANT_ID }}
            subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
  create-deployment:
      uses: ./.github/workflows/create-deployment.yml
      needs: [get-config,create-endpoint]
      with:
        resource_group: ${{ needs.get-config.outputs.resource_group }}
        workspace_name: ${{ needs.get-config.outputs.aml_workspace }} 
        endpoint_file: mlops/azureml/deploy/online/online-deployment.yml
        endpoint_name: nlp-summarization-online-dp
        endpoint_type: online
        deployment_name: nlp-summarization-online-dp
      secrets:
        client-id: ${{ secrets.AZURE_CLIENT_ID }}
        tenant-id: ${{ secrets.AZURE_TENANT_ID }}
        subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
  allocate-traffic:
      uses: ./.github/workflows/allocate-traffic.yml
      needs: [get-config,create-deployment]
      with:
        resource_group: ${{ needs.get-config.outputs.resource_group }}
        workspace_name: ${{ needs.get-config.outputs.aml_workspace }} 
        traffic_allocation: nlp-summarization-online-dp=100
        endpoint_name: nlp-summarization-online-dp
      secrets:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
